### ISSUE TITLE
Service does not start

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/ghost_ynh#12]
Hi,
Installation is successful and does not report any error. However, I am faced with a `Bad gateway error` due to the service not started up. `journalctl -xe` reports:

```
Sep 08 18:47:50 vps systemd[1]: Started ghost systemd service.
-- Subject: Unit ghost.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit ghost.service has finished starting up.
--
-- The start-up result is done.
Sep 08 18:47:50 vps node[23468]: /var/www/ghost/core/server/index.js:18
Sep 08 18:47:50 vps node[23468]: let parentApp;
Sep 08 18:47:50 vps node[23468]: ^^^
Sep 08 18:47:50 vps node[23468]: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Sep 08 18:47:50 vps node[23468]:     at exports.runInThisContext (vm.js:53:16)
Sep 08 18:47:50 vps node[23468]:     at Module._compile (module.js:373:25)
Sep 08 18:47:50 vps node[23468]:     at Object.Module._extensions..js (module.js:416:10)
Sep 08 18:47:50 vps node[23468]:     at Module.load (module.js:343:32)
Sep 08 18:47:50 vps node[23468]:     at Function.Module._load (module.js:300:12)
Sep 08 18:47:50 vps node[23468]:     at Module.require (module.js:353:17)
Sep 08 18:47:50 vps node[23468]:     at require (internal/module.js:12:17)
Sep 08 18:47:50 vps node[23468]:     at Object.<anonymous> (/var/www/ghost/core/index.js:3:16)
Sep 08 18:47:50 vps node[23468]:     at Module._compile (module.js:409:26)
Sep 08 18:47:50 vps node[23468]:     at Object.Module._extensions..js (module.js:416:10)
Sep 08 18:47:50 vps systemd[1]: ghost.service: Main process exited, code=exited, status=1/FAILURE
Sep 08 18:47:50 vps systemd[1]: ghost.service: Unit entered failed state.
Sep 08 18:47:50 vps systemd[1]: ghost.service: Failed with result 'exit-code'.
Sep 08 18:47:50 vps systemd[1]: ghost.service: Service hold-off time over, scheduling restart.
Sep 08 18:47:50 vps systemd[1]: lvm2-lvmetad.socket: Cannot add dependency job, ignoring: Unit lvm2-lvmetad.socket is masked.
Sep 08 18:47:50 vps systemd[1]: lvm2-monitor.service: Cannot add dependency job, ignoring: Unit lvm2-monitor.service is masked.
Sep 08 18:47:50 vps systemd[1]: lvm2-activation.service: Cannot add dependency job, ignoring: Unit lvm2-activation.service is masked.
Sep 08 18:47:50 vps systemd[1]: lvm2-activation-early.service: Cannot add dependency job, ignoring: Unit lvm2-activation-early.service is masked.
Sep 08 18:47:50 vps systemd[1]: Stopped ghost systemd service.
-- Subject: Unit ghost.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit ghost.service has finished shutting down.
```

**Comment by anmol26s** [comment]
Can you show install logs? Is there warning for some dependency?
Maybe try yourself to install dependency and see for yourself and restart ghost service?

```
$ cd /var/www/ghost
$ yarn install 
$ yarn global add knex-migrator
$ NODE_ENV=production knex-migrator init
```

**Comment by jeremy54** [comment]
It doesn't work...

The engine "node" is incompatible with this module. Expected version "^6.9.0 || ^8.9.0"

**Comment by anmol26s** [comment]
@jeremy54 
The command install node 8.11 from install script 
https://github.com/YunoHost-Apps/ghost_ynh/blob/master/scripts/install#L78

You should have node 8.11. Can you check?

**Comment by tituspijean** [comment]
I had missed your request for installation logs, sorry.
I have just tried installing it again, and no problem.

Considering the age of the issue, let's close.
