### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by op3nus3r** [YunoHost-Apps/ghost_ynh#13]
Hello,
I tried to install the Ghost package on my raspberry pi 3 with yunohost v.3.2 stable.

The first installation failed (unfortunately I don't have the logs). During installation I changed the default path, I don't know if this is the cause of the error.
I uninstalled the package.
I reinstalled it with the default options and the installation worked but when I connect to the site I get a **Nginx 502 Bad Gateway error**.

```
2018-10-26 22:33:59,441: WARNING - 'yunohost app checkurl' is deprecated and will be removed in the future
2018-10-26 22:33:59,646: WARNING - Packagers /!\ : 'app checkurl' is deprecated ! Please use the helper 'ynh_webpath_register' instead !
2018-10-26 22:34:09,783: WARNING - E: Unable to correct problems, you have held broken packages.
2018-10-26 22:34:09,886: WARNING - --2018-10-26 22:34:09--  https://en.ghost.org/zip/ghost-0.5.1.zip
2018-10-26 22:34:10,089: WARNING - Resolving en.ghost.org (en.ghost.org)... 104.16.32.191, 104.16.35.191, 104.16.33.191, ...
2018-10-26 22:34:10,091: WARNING - Connecting to en.ghost.org (en.ghost.org)|104.16.32.191|:443... connected.
2018-10-26 22:34:10,193: WARNING - HTTP request sent, awaiting response... 301 Moved Permanently
2018-10-26 22:34:10,195: WARNING - Location: https://ghost.org/zip/ghost-0.5.1.zip [following]
2018-10-26 22:34:10,196: WARNING - --2018-10-26 22:34:10--  https://ghost.org/zip/ghost-0.5.1.zip
2018-10-26 22:34:10,299: WARNING - Resolving ghost.org (ghost.org)... 104.16.127.190, 104.16.34.191, 104.16.33.191, ...
2018-10-26 22:34:10,300: WARNING - Connecting to ghost.org (ghost.org)|104.16.127.190|:443... connected.
2018-10-26 22:34:10,503: WARNING - HTTP request sent, awaiting response... 301 Moved Permanently
2018-10-26 22:34:10,505: WARNING - Location: /zip/ghost-0.5.1.zip/ [following]
2018-10-26 22:34:10,508: WARNING - --2018-10-26 22:34:10--  https://ghost.org/zip/ghost-0.5.1.zip/
2018-10-26 22:34:10,510: WARNING - Reusing existing connection to ghost.org:443.
2018-10-26 22:34:10,513: WARNING - HTTP request sent, awaiting response... 404 Not Found
2018-10-26 22:34:10,515: WARNING - 2018-10-26 22:34:10 ERROR 404: Not Found.
2018-10-26 22:34:10,517: WARNING - 
2018-10-26 22:34:10,620: WARNING -   End-of-central-directory signature not found.  Either this file is not
2018-10-26 22:34:10,622: WARNING -   a zipfile, or it constitutes one disk of a multi-part archive.  In the
2018-10-26 22:34:10,624: WARNING -   latter case the central directory and zipfile comment will be found on
2018-10-26 22:34:10,626: WARNING -   the last disk(s) of this archive.
2018-10-26 22:34:10,628: WARNING - unzip:  cannot find zipfile directory in one of ../tmp/ghost-0.5.1.zip or
2018-10-26 22:34:10,630: WARNING -         ../tmp/ghost-0.5.1.zip.zip, and cannot find ../tmp/ghost-0.5.1.zip.ZIP, period.
2018-10-26 22:34:11,235: WARNING - cp: cannot stat '../tmp/ghost': No such file or directory
2018-10-26 22:34:12,642: WARNING - bash: line 0: cd: /var/www/ghostblog/ghost: No such file or directory
2018-10-26 22:34:13,248: WARNING - cp: cannot stat '/var/www/ghostblog/ghost/core/server/views/user-error.hbs': No such file or directory
2018-10-26 22:34:13,351: WARNING - cp: cannot stat '/var/www/ghostblog/ghost/core/server/views/default.hbs': No such file or directory
2018-10-26 22:34:13,354: WARNING - cp: cannot stat '/var/www/ghostblog/ghost/core/client/assets/css/fonts.css': No such file or directory
2018-10-26 22:34:13,559: WARNING - sed: can't read /var/www/ghostblog/ghost/core/server/views/user-error.hbs: No such file or directory
2018-10-26 22:34:13,561: WARNING - sed: can't read /var/www/ghostblog/ghost/core/server/views/default.hbs: No such file or directory
2018-10-26 22:34:13,663: WARNING - cp: cannot create regular file '/var/www/ghostblog/ghost/core/client/assets/css': No such file or directory
2018-10-26 22:34:13,766: WARNING - cp: target '/var/www/ghostblog/ghost/core/client/assets/fonts' is not a directory
2018-10-26 22:34:13,869: WARNING - cp: cannot stat '/var/www/ghostblog/ghost/content/themes/casper/default.hbs': No such file or directory
2018-10-26 22:34:13,972: WARNING - cp: cannot stat '/var/www/ghostblog/ghost/content/themes/casper/assets/css/fonts.css': No such file or directory
2018-10-26 22:34:13,975: WARNING - sed: can't read /var/www/ghostblog/ghost/content/themes/casper/default.hbs: No such file or directory
2018-10-26 22:34:14,078: WARNING - cp: cannot create regular file '/var/www/ghostblog/ghost/content/themes/casper/assets/css': No such file or directory
2018-10-26 22:34:14,180: WARNING - cp: target '/var/www/ghostblog/ghost/content/themes/casper/assets/fonts' is not a directory
2018-10-26 22:34:14,282: WARNING - chown: cannot access '/var/www/ghostblog/ghost': No such file or directory
2018-10-26 22:34:15,388: WARNING - 'yunohost app initdb' is deprecated and will be removed in the future
2018-10-26 22:34:15,591: WARNING - Packagers /!\ : 'app initdb' is deprecated ! Please use the helper 'ynh_mysql_setup_db' instead !
2018-10-26 22:34:17,199: WARNING - chown: cannot access '/var/www/ghostblog/ghost/config.js': Not a directory
2018-10-26 22:34:17,301: WARNING - chmod: cannot access '/var/www/ghostblog/ghost/config.js': Not a directory
2018-10-26 22:34:29,644: WARNING - Traceback (most recent call last):
2018-10-26 22:34:29,646: WARNING -   File "../conf/user_getname.py", line 3, in <module>
2018-10-26 22:34:29,650: WARNING -     if i["username"] == sys.argv[1]:
2018-10-26 22:34:29,653: WARNING - TypeError: string indices must be integers
2018-10-26 22:34:30,860: WARNING - Traceback (most recent call last):
2018-10-26 22:34:30,862: WARNING -   File "../conf/user_getmail.py", line 3, in <module>
2018-10-26 22:34:30,864: WARNING -     if i["username"] == sys.argv[1]:
2018-10-26 22:34:30,865: WARNING - TypeError: string indices must be integers
2018-10-26 22:34:30,967: WARNING -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2018-10-26 22:34:30,969: WARNING -                                  Dload  Upload   Total   Spent    Left  Speed
2018-10-26 22:34:31,071: WARNING - 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 2368: Connection refused
2018-10-26 22:34:35,364: SUCCESS - La configuration de SSOwat a Ã©tÃ© gÃ©nÃ©rÃ©e
2018-10-26 22:34:35,366: SUCCESS - Installation terminÃ©e
```

I also wanted to specify that the package is marked as "not working" in the list of community applications. I don't know if this is an oversight.

**Comment by anmol26s** [comment]
Can you please test the app after installing the nodejs? I can not find any problem in the package other then having nodejs path with global location rather then location defined for nodejs for particular app.

Install nodejs 8 with the commands given in the link:
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

And then try to install ghost pack again and see if the 502 error disappear. I would like to see if broken package error is from the failed attempt or successful attempt with 502 error.

**Comment by op3nus3r** [comment]
hi @anmol26s ,
I installed nodejs 8 as requested, but I still have error 502.
I noticed that the ynh_ghostblog service was stopped after installing ghost_yhn, I restarted it, I also tried to restart the server. The ynh_ghostblog service is active but it's always the same, I still have error 502, here are my installation logs: 


```
2018-10-28 13:05:55,470: WARNING - Resolving ghost.org (ghost.org)... 104.16.127.190, 104.16.35.191, 104.16.34.191, ...
2018-10-28 13:05:55,473: WARNING - Connecting to ghost.org (ghost.org)|104.16.127.190|:443... connected.
2018-10-28 13:05:55,677: WARNING - HTTP request sent, awaiting response... 301 Moved Permanently
2018-10-28 13:05:55,680: WARNING - Location: /zip/ghost-0.5.1.zip/ [following]
2018-10-28 13:05:55,683: WARNING - --2018-10-28 13:05:55--  https://ghost.org/zip/ghost-0.5.1.zip/
2018-10-28 13:05:55,686: WARNING - Reusing existing connection to ghost.org:443.
2018-10-28 13:05:55,789: WARNING - HTTP request sent, awaiting response... 404 Not Found
2018-10-28 13:05:55,793: WARNING - 2018-10-28 13:05:55 ERROR 404: Not Found.
2018-10-28 13:05:55,796: WARNING - 
2018-10-28 13:05:55,899: WARNING -   End-of-central-directory signature not found.  Either this file is not
2018-10-28 13:05:55,902: WARNING -   a zipfile, or it constitutes one disk of a multi-part archive.  In the
2018-10-28 13:05:55,905: WARNING -   latter case the central directory and zipfile comment will be found on
2018-10-28 13:05:55,908: WARNING -   the last disk(s) of this archive.
2018-10-28 13:05:55,910: WARNING - unzip:  cannot find zipfile directory in one of ../tmp/ghost-0.5.1.zip or
2018-10-28 13:05:55,913: WARNING -         ../tmp/ghost-0.5.1.zip.zip, and cannot find ../tmp/ghost-0.5.1.zip.ZIP, period.
2018-10-28 13:05:56,621: WARNING - cp: cannot stat '../tmp/ghost': No such file or directory
2018-10-28 13:05:58,229: WARNING - bash: line 0: cd: /var/www/ghostblog/ghost: No such file or directory
2018-10-28 13:05:58,838: WARNING - cp: cannot stat '/var/www/ghostblog/ghost/core/server/views/user-error.hbs': No such file or directory
2018-10-28 13:05:58,840: WARNING - cp: cannot stat '/var/www/ghostblog/ghost/core/server/views/default.hbs': No such file or directory
2018-10-28 13:05:58,942: WARNING - cp: cannot stat '/var/www/ghostblog/ghost/core/client/assets/css/fonts.css': No such file or directory
2018-10-28 13:05:59,044: WARNING - sed: can't read /var/www/ghostblog/ghost/core/server/views/user-error.hbs: No such file or directory
2018-10-28 13:05:59,147: WARNING - sed: can't read /var/www/ghostblog/ghost/core/server/views/default.hbs: No such file or directory
2018-10-28 13:05:59,250: WARNING - cp: cannot create regular file '/var/www/ghostblog/ghost/core/client/assets/css': No such file or directory
2018-10-28 13:05:59,253: WARNING - cp: target '/var/www/ghostblog/ghost/core/client/assets/fonts' is not a directory
2018-10-28 13:05:59,355: WARNING - cp: cannot stat '/var/www/ghostblog/ghost/content/themes/casper/default.hbs': No such file or directory
2018-10-28 13:05:59,458: WARNING - cp: cannot stat '/var/www/ghostblog/ghost/content/themes/casper/assets/css/fonts.css': No such file or directory
2018-10-28 13:05:59,561: WARNING - sed: can't read /var/www/ghostblog/ghost/content/themes/casper/default.hbs: No such file or directory
2018-10-28 13:05:59,665: WARNING - cp: cannot create regular file '/var/www/ghostblog/ghost/content/themes/casper/assets/css': No such file or directory
2018-10-28 13:05:59,768: WARNING - cp: target '/var/www/ghostblog/ghost/content/themes/casper/assets/fonts' is not a directory
2018-10-28 13:05:59,770: WARNING - chown: cannot access '/var/www/ghostblog/ghost': No such file or directory
2018-10-28 13:06:01,076: WARNING - 'yunohost app initdb' is deprecated and will be removed in the future
2018-10-28 13:06:01,379: WARNING - Packagers /!\ : 'app initdb' is deprecated ! Please use the helper 'ynh_mysql_setup_db' instead !
2018-10-28 13:06:04,392: WARNING - chown: cannot access '/var/www/ghostblog/ghost/config.js': Not a directory
2018-10-28 13:06:04,494: WARNING - chmod: cannot access '/var/www/ghostblog/ghost/config.js': Not a directory
2018-10-28 13:11:09,146: WARNING - Job for ynh-ghostblog.service failed because a timeout was exceeded.
2018-10-28 13:11:09,151: WARNING - See "systemctl status ynh-ghostblog.service" and "journalctl -xe" for details.
2018-10-28 13:11:19,089: WARNING - Traceback (most recent call last):
2018-10-28 13:11:19,091: WARNING -   File "../conf/user_getname.py", line 3, in <module>
2018-10-28 13:11:19,093: WARNING -     if i["username"] == sys.argv[1]:
2018-10-28 13:11:19,096: WARNING - TypeError: string indices must be integers
2018-10-28 13:11:20,403: WARNING - Traceback (most recent call last):
2018-10-28 13:11:20,405: WARNING -   File "../conf/user_getmail.py", line 3, in <module>
2018-10-28 13:11:20,407: WARNING -     if i["username"] == sys.argv[1]:
2018-10-28 13:11:20,409: WARNING - TypeError: string indices must be integers
2018-10-28 13:11:20,511: WARNING -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2018-10-28 13:11:20,513: WARNING -                                  Dload  Upload   Total   Spent    Left  Speed
2018-10-28 13:11:20,515: WARNING - 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 2368: Connection refused
2018-10-28 13:11:24,916: SUCCESS - La configuration de SSOwat a été générée
2018-10-28 13:11:24,918: SUCCESS - Installation terminée
```

**Comment by anmol26s** [comment]
Are you installing the app from **admin-web** interface? :worried: 
The admin-interface has not been updated from ages as you know it states not-working.
Try the command-line way to get the updated version if you not installing from the command-line:

`$ yunohost app install --debug https://github.com/YunoHost-Apps/ghost_ynh`

**Comment by anmol26s** [comment]
Meanwhile I have updated the sources. I think now you can try from web-admin interface too. It should point to the latest sources now.

**Comment by anmol26s** [comment]
The error comes from : 

`26100 WARNING This url is not available or conflicts with the already installed app(s):`
This means that /blog path is taken already.
Try on other path.
Do 
`$ yunohsot app remove --debug ghost`
Install again with any other subpath like /blogging 
`$ yunohost app install --debug https://github.com/YunoHost-Apps/ghost_ynh`

**Comment by op3nus3r** [comment]
Great, it works.
Thank you for your help.

During the installation I thought it had crashed, 

```
264964 DEBUG [5/5] Building fresh packages...
752881 DEBUG success Saved lockfile.
753630 DEBUG Done in **638.76s.**
```
Installed on my RaspberryPi3 

Apparently everything seems to be working well.
Thank you again.

**Comment by anmol26s** [comment]
It takes time for yarn install and onRaspberryPi3 it can take little longer, that  is why you should use command-line when ever its possible.

**Comment by op3nus3r** [comment]
I'm not a power-user but I'm going to try :D 
Thank you for your patience.

**Comment by tituspijean** [comment]
Almost 3 years later, let's assume it's fixed. 😇
