### ISSUE TITLE
ghost failing to start on SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported ou tside strict mode

### ISSUE THREAD

**Issue by arthurlogilab** [YunoHost-Apps/ghost_ynh#18]
```
Jan  8 08:39:14 y systemd[1]: Started ghost systemd service.
Jan  8 08:39:14 y node[3282]: /var/www/ghost/node_modules/ghost-ignition/node_modules/debug/src/node.js:132
Jan  8 08:39:14 y node[3282]: #011let val = process.env[key];
Jan  8 08:39:14 y node[3282]: #011^^^
Jan  8 08:39:14 y node[3282]: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported ou
tside strict mode
Jan  8 08:39:14 y node[3282]:     at exports.runInThisContext (vm.js:53:16)
Jan  8 08:39:14 y node[3282]:     at Module._compile (module.js:373:25)
Jan  8 08:39:14 y node[3282]:     at Object.Module._extensions..js (module.js:416:10)
Jan  8 08:39:14 y node[3282]:     at Module.load (module.js:343:32)
Jan  8 08:39:14 y node[3282]:     at Function.Module._load (module.js:300:12)
Jan  8 08:39:14 y node[3282]:     at Module.require (module.js:353:17)
Jan  8 08:39:14 y node[3282]:     at require (internal/module.js:12:17)
Jan  8 08:39:14 y node[3282]:     at Object.<anonymous> (/var/www/ghost/node_modules/ghost-ignition/node_modules/debug/
src/index.js:9:19)
Jan  8 08:39:14 y node[3282]:     at Module._compile (module.js:409:26)
Jan  8 08:39:14 y node[3282]:     at Object.Module._extensions..js (module.js:416:10)
Jan  8 08:39:14 y systemd[1]: ghost.service: Main process exited, code=exited, status=1/FAILURE
Jan  8 08:39:14 y systemd[1]: ghost.service: Unit entered failed state.
Jan  8 08:39:14 y systemd[1]: ghost.service: Failed with result 'exit-code'.
Jan  8 08:39:14 y systemd[1]: ghost.service: Service hold-off time over, scheduling restart.
Jan  8 08:39:14 y systemd[1]: Stopped ghost systemd service.
Jan  8 08:39:14 y systemd[1]: ghost.service: Start request repeated too quickly.
Jan  8 08:39:14 y systemd[1]: Failed to start ghost systemd service.
Jan  8 08:39:14 y systemd[1]: ghost.service: Unit entered failed state.
Jan  8 08:39:14 y systemd[1]: ghost.service: Failed with result 'exit-code'.
```
Seem to be related to an old version of node : 

```
# node --version
v4.8.2
```

**Comment by arthurlogilab** [comment]
Related to fix tried in  #17 

With a more recent version of node : 

```
# /opt/node_n/bin/node --version
v8.17.0
```

It seems to work better. Is node shipped with this yunohost app?

**Comment by anmol26s** [comment]
Can someone test this branch and see if the issue is fixed?

`$ yunohost app install --debug https://github.com/YunoHost-Apps/ghost_ynh/tree/admin-fix `

**Comment by arthurlogilab** [comment]
Sorry, not using ghost anymore.
