### ISSUE TITLE
ghost 5.21 doesn't work with MariaBD 

### ISSUE THREAD

**Issue by rontst** [YunoHost-Apps/ghost_ynh#199]
Installed a new instance of Ghost using the admin panel and it displays an error when trying to perform any operation with posts (list, create, save, delete). Error says  "Request not understood error, cannot list posts. Could not understand request."

- Hardware: VPS bought online (8GB RAM)
- YunoHost version: 11.0.10.2 (stable)
- I have access to my server: through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- Using, or trying to install package version/branch:

- If the error occurs in your browser, explain what you did:
   1. Install ghost current version (5.21)
   2. Click on Posts - Error shows -   "Request not understood error, cannot list posts. Could not understand request."
   3. Any other operation on posts shows the same message

According to the Ghost Forums this issue happens because version 5.21 does not support MariaDB (while v5.20 did) link: https://forum.ghost.org/t/post-only-error-request-not-understood-error-cannot-list-posts-could-not-understand-request/33768

This is a fresh install but I have some other instances of Ghost on this server... is moving those instances to mysql feasible? since MariaDB is no longer supported?

Screenshot:
![image](https://user-images.githubusercontent.com/68206722/200099694-3f4260c0-1cde-4184-acbb-c94355ef7494.png)

Thanks for all your work on this!!

**Comment by Neso2** [comment]
I have the same issue. Fresh installation today and same error!

`journalctl
-- Journal begins at Sat 2022-10-29 00:52:03 CEST, ends at Sat 2022-11-05 14:04:05 CET. --
Nov 05 12:55:00 yarn[30113]: [2022-11-05 11:55:00] INFO "GET /blog/ghost/api/admin/stats/referrers/" 200 64ms
Nov 05 12:55:00 yarn[30113]: [2022-11-05 11:55:00] INFO "GET /blog/ghost/api/admin/members/?filter=newsletters.status%3Aactive%2Bstatus%3A-free&limit=1&page=1&include=newsletters%2Clabels" 200 93ms
Nov 05 12:55:00 yarn[30113]: [2022-11-05 11:55:00] INFO "GET /blog/ghost/api/admin/members/?filter=newsletters.status%3Aactive%2Bstatus%3Afree&limit=1&page=1&include=newsletters%2Clabels" 200 99ms
Nov 05 12:55:00 yarn[30113]: [2022-11-05 11:55:00] INFO "GET /blog/ghost/api/admin/members/?filter=last_seen_at%3A%3E2022-10-05T22%3A00%3A00.000Z&limit=1&page=1&include=newsletters%2Clabels" 200 110ms
Nov 05 12:55:00 yarn[30113]: [2022-11-05 11:55:00] INFO "GET /blog/ghost/api/admin/members/?filter=last_seen_at%3A%3E2022-10-28T22%3A00%3A00.000Z&limit=1&page=1&include=newsletters%2Clabels" 200 112ms
Nov 05 12:55:00 yarn[30113]: [2022-11-05 11:55:00] INFO "GET /blog/ghost/api/admin/stats/member_count/" 200 81ms
Nov 05 12:55:00 yarn[30113]: [2022-11-05 11:55:00] ERROR "GET /blog/ghost/api/admin/posts/?formats=mobiledoc%2Clexical&limit=5&filter=status%3A%5Bpublished%2Csent%5D&order=published_at%20desc" 400 107ms
Nov 05 12:55:00 yarn[30113]: 
Nov 05 12:55:00 yarn[30113]: Could not understand request.
Nov 05 12:55:00 yarn[30113]: Error ID:
Nov 05 12:55:00 yarn[30113]:     ad5b0500-5d00-11ed-a853-b369e0986dd5
Nov 05 12:55:00 yarn[30113]: Error Code: 
Nov 05 12:55:00 yarn[30113]:     ER_BAD_FIELD_ERROR
Nov 05 12:55:00 yarn[30113]: ----------------------------------------
Nov 05 12:55:00 yarn[30113]: Error: select `posts`.*, (with `k` as (select `member_id` from `members_subscription_created_events` where posts.id = members_subscription_created_events.attribution_id union select `member_id` from `members_created_events` where posts.id = members_created_events.attribution_id) select count(*) from `k`) as `count__conversions`, `posts`.*, (select count(distinct `members_click_events`.`member_id`) from `members_click_events` inner join `redirects` on `members_click_events`.`redirect_id` = `redirects`.`id` where posts.id = redirects.post_id) as `count__clicks`, `posts`.*, (select COALESCE(ROUND(AVG(score) * 100), 0) from `members_feedback` where posts.id = members_feedback.post_id) as `count__sentiment`, `posts`.*, (select count(*) from `members_feedback` where posts.id = members_feedback.post_id AND members_feedback.score = 0) as `count__negative_feedback`, `posts`.*, (select sum(`score`) from `members_feedback` where posts.id = members_feedback.post_id) as `count__positive_feedback` from `posts` where (`posts`.`status` in ('published', 'sent') and `posts`.`type` = 'post') order by `posts`.`published_at` DESC limit 5 - Unknown column 'posts.id' in 'where clause'
Nov 05 12:55:00 yarn[30113]:     at /var/www/ghost/node_modules/@tryghost/bookshelf-pagination/lib/bookshelf-pagination.js:259:27
Nov 05 12:55:00 yarn[30113]:     at Packet.asError (/var/www/ghost/node_modules/mysql2/lib/packets/packet.js:728:17)
Nov 05 12:55:00 yarn[30113]:     at Query.execute (/var/www/ghost/node_modules/mysql2/lib/commands/command.js:29:26)
Nov 05 12:55:00 yarn[30113]:     at Connection.handlePacket (/var/www/ghost/node_modules/mysql2/lib/connection.js:456:32)
Nov 05 12:55:00 yarn[30113]:     at PacketParser.onPacket (/var/www/ghost/node_modules/mysql2/lib/connection.js:85:12)
Nov 05 12:55:00 yarn[30113]:     at PacketParser.executeStart (/var/www/ghost/node_modules/mysql2/lib/packet_parser.js:75:16)
Nov 05 12:55:00 yarn[30113]:     at Socket.<anonymous> (/var/www/ghost/node_modules/mysql2/lib/connection.js:92:25)
Nov 05 12:55:00 yarn[30113]:     at Socket.emit (events.js:400:28)
Nov 05 12:55:00 yarn[30113]:     at addChunk (internal/streams/readable.js:293:12)
Nov 05 12:55:00 yarn[30113]:     at readableAddChunk (internal/streams/readable.js:267:9)
Nov 05 12:55:00 yarn[30113]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
Nov 05 12:55:00 yarn[30113]:     at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Nov 05 12:55:00 yarn[30113]: `

**Comment by tituspijean** [comment]
Thank you for your investigation! Confirmed there too: https://github.com/TryGhost/Ghost/issues/15729

Having concurrent installations of MySQL and MariaDB does not seem feasible. YunoHost has an even smaller contributor team, and I have no time, no will, nor skill to handle this matter.

I will revert the repository to v5.20 and freeze upgrades as long as the issue remains. I will keep the versions above 5.21 in the `master-5.21+` branch.

**Comment by rontst** [comment]
That makes total sense. Thanks for all your work here!!

Luckily I don't have much content in my sites, so I'll be able to export, remove all the instances, and then reinstall them with mysql v5.21+ (when ready), and import the content.

Again, thanks a lot!!

**Comment by tituspijean** [comment]
@rontst @Neso2 I might have found a temporary workaround to fix the issue. Would you mind trying it?

`sudo yunohost app install https://github.com/YunoHost-Apps/ghost_ynh -f`

**Comment by freddewitt** [comment]
It worked for me on RPI 4 !
![Capture d’écran 2023-01-06 à 08 17 20](https://user-images.githubusercontent.com/15184529/210950726-f666e960-838a-4cd2-ae52-07a63b0845e4.png)

The export / import content by JSON file is working
The export / import users is working
Everything aout article is working
Still a warning of using MariadB in "info"
I just have to upload media picture of the article, but this very fine 

Thanks a lot

**Comment by remcoboerma** [comment]
unfortunately the testing is currently updated upto 5.30, which breaks the admin screen. so don't repeat the above mentioned yunohost app install command anymore.
