### ISSUE TITLE
Can't upgrade my ghost instance

### ISSUE THREAD

**Issue by loic-moriame** [YunoHost-Apps/ghost_ynh#233]
### Describe the bug

I try to upgrade my Ghost instance and get an error

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.1.19
- I have access to my server: *Through SSH & webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- If upgrading, current package version: *5.26.4~ynh1*

### Steps to reproduce

```sh
sudo yunohost app upgrade ghost
```

### Expected behavior

I would like to upgrade my ghost instance to the latest one available

### Logs

```sh
admin@yunohost:~$ sudo yunohost app upgrade ghost
[sudo] password for admin:
Info: Now upgrading ghost...
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 77, in <module>
    yunohost.cli(
  File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 41, in cli
    ret = moulinette.cli(
  File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 111, in cli
    Cli(
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 507, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 584, in process
    return func(**arguments)
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 676, in app_upgrade
    notifications = _filter_and_hydrate_notifications(
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 3142, in _filter_and_hydrate_notifications
    return {
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 3148, in <dictcomp>
    or is_version_more_recent_than_current_version(name)
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 3134, in is_version_more_recent_than_current_version
    current_version = str(current_version)
UnboundLocalError: local variable 'current_version' referenced before assignment
```

**Comment by tituspijean** [comment]
It looks like a side effect of https://github.com/YunoHost/yunohost/pull/1655, what do you think @alexAubin ?
